using System;

using MoonSharp.Interpreter;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;

using CoreEngine.Lua;

namespace CoreEngine.ECS
{
	// The goal is to use Lua scripting for all gameplay and interactive elements
	// The scripts should be: 
	// * files from a hard drive, 
	// * files from the network network via IPFS or HTTP GET 
	// * procedurally generated by a user / AI from within the app.
	public class Scriptable : Component
    {
		public LuaScript LuaScript;

        public Scriptable(string script)
        {
			LuaScript = new LuaScript(script);
        }

		public override void Initialize(Entity entity)
		{
			LuaScript.AddAPI(entity);
			LuaScript.Initialize();
			base.Initialize(entity);
		}

		public override void Update(float dt)
		{
			LuaScript.Update(dt);
			base.Update(dt);
		}
	}
}